routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\SearchImageController;
use App\Http\Controllers\LikedImageController;
use App\Http\Requests\SearchImageRequest;
use App\Http\Controllers\UtilisateurController;
use App\Http\Controllers\CommentaireFormController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});


/** Permet de faire fonctionner la barre de recherche  */
Route::get('search_image',[SearchImageController::class, 'getInfos']);
Route::post('search_image',[SearchImageController::class, 'postInfos']);

/** Permet de faire aimer une image  */
Route::get('liked_image',[LikedImageController::class, 'getInfos']);
Route::post('liked_image',[LikedImageController::class, 'postInfos']);

/** Permet de mettre des commentaires sur des images */
Route::get('post_comment',[CommentaireFormController::class, 'getInfos']);
Route::post('post_comment',[CommentaireFormController::class, 'postInfos']);

/** Page d'accueil de quelqu'un qui se connecte */
Route::resource('images',ImageController::class);
Route::resource('personalInfo', UtilisateurController::class);






Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/confirmImageAdded.blade.php
@extends('layouts.layout')

@section('title')
    Image ajoutée avec succès
@endsection

@section('correction_url')../@endsection

@section('page_contenu')
<div class="alert alert-success text-center w-50 mx-auto mt-5" role="alert">
    
  Votre image a été ajoutée avec succès !
  <a href="{{route('personalInfo.show',Auth::user()->id)}}" class="">Retour à votre page</a>
  
</div>

<div style="width:480px" class="text-center mx-auto"><iframe allow="fullscreen" frameBorder="0" height="400" src="https://giphy.com/embed/qm4OiHF2wGoq7onwrn/video" width="480"></iframe></div>

@endsection

resources/views/createImage.blade.php
@extends('layouts.layout')

@section('title')
    Ajouter une image
@endsection

@section('correction_url')../@endsection

@section('page_contenu')
<div class="container">
    <div class="row shadow card text-black w-50 mx-auto p-3" style="background-color:rgb(27,30,31);">
        <p class="text-center display-5">Publier une image</p>  
        <form action="{{route('images.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group mt-4">
                <label for="title" class="form-label col-md-5 col-10">Titre de l'image</label>
                <input id="title" class="border form-control col-md-3 text-light shadow col-6"  name="title" style="background-color:rgb(24,26,27);border:1px solid rgb(50,54,56);" type="text" placeholder="Mon animal preferé"/>
                @error('title')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group row mt-4">
                <label for="description" class="form-label col-md-5 col-10">Description</label>
                <textarea id="description" class="border form-control text-light col-md-3 shadow col-6" style="background-color:rgb(24,26,27);"  name="description" type="textarea" placeholder="Je l'aime tellement"></textarea>
                @error('description')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group row mt-4">
            <label for="id_genre" class="form-label col-md-5 col-10">Genre</label>
            <select name="id_genre" name="id_genre" id="id_genre" style="background-color:rgb(24,26,27);" class="form-select text-light">
            @foreach($listeGenre as $genre)
                    <option class="text-light" value="{{$genre->id}}" {{ ( $genre->id == $genre_id) ? 'selected' : '' }}>{{$genre->genreName}}</option>
            @endforeach
            </select>
            
            </div>

            <div class="form-group row mt-4">
                <label for="source" name="source" class="label-file" >Choisir une image</label>
                <input id="source" name="source" class="input-file mt-3 text-light" type="file">
                @error('source')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="justify-content-end mt-4 text-center">
                <button type="submit" class="btn btn-success">Publier !</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/homeConnected.blade.php
@extends('layouts.layout')

@section('title')
    Home
@endsection

@section('page_contenu')

<?php $i=1; ?>
<?php $nbImages=0;?>
<div class="pin_container">

@foreach($images as $image)
<?php
    
    if($i==1)
    {
        
        echo '<a href="'.route('images.show',$image->id).'" data="'.$nbImages.'" class="card card_small">';
        $i = $i+1;
    }
    else if($i==2)
    {
        echo '<a href="'.route('images.show',$image->id).'" data="'.$nbImages.'" class="card card_medium">';
        $i = $i+1;
    }
    else
    {
        echo '<a href="'.route('images.show',$image->id).'" data="'.$nbImages.'" class="card card_large">';
        $i = 1;
    }
    
    
?>
    <img class="card-img-top rounded" width="400" height="500" src="{{ asset($image->source) }}" alt="">
    <?php $nbImages = $nbImages+1?>
    
</a>
@endforeach
</div>  

@endsection

@section('script')
/*var classname = document.getElementsByClassName("card");
var classbutton = document.getElementsByClassName("bouton_aimer");

var visible = function() {
    var attribute = this.getAttribute("data");
    var button = document.getElementById("bouton"+attribute);
    button.style.visibility = 'visible';
};

var cacher = function() {
    var attribute = this.getAttribute("data");
    var button = document.getElementById("bouton"+attribute);
    button.style.visibility = 'hidden';
};


for (var i = 0; i < classname.length; i++) {
    classname[i].addEventListener('mouseover', visible, false);
}

for (var i = 0; i < classname.length; i++) {
    classname[i].addEventListener('mouseout', cacher, false);
}*/
@endsection

resources/views/index.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{asset('assets/css/accueil.css')}}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <title>AnimalsHub - France</title>
</head>
<body style="overflow: hidden;" class="bg-dark">
    <div>
        <nav class="navbar navbar-expand-lg bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand text-light " href="#">AnimalsHub</a>
            @if (Route::has('login'))
                <div class="hidden fixed top-0 right-0 px-6 sm:block">
                    @auth
                        <a href="{{ route('images.index') }}" class="text-sm text-gray-700 dark:text-gray-500 btn btn-success rounded-pill underline">Aller sur le site</a>
                    @else
                        <a href="{{ route('login') }}" class="text-sm text-gray-700 dark:text-gray-500 btn btn-danger rounded-pill underline">Se connecter</a>

                        @if (Route::has('register'))
                            <a href="{{ route('register') }}" class="ml-4 text-sm text-gray-700 dark:text-gray-500 underline btn btn-light rounded-pill">S'inscrire</a>
                        @endif
                    @endauth
                </div>
            @endif
            </div>
        </div>  

        </nav>

        <div class="bd-example bg-light mt-2 bg-dark">
        <div class="mx-auto text-center">
            <img width="150" height="150" class="rounded-circle text-center" src="{{asset('assets/img/iconesPdp/logo2.png')}}"/>
        </div>
            <p class="text-center display-5 text-white">Un site pour les amis des animaux</p>
            <p class="text-center display-5 text-white">+ de 750 000 images</p>
            <div class="d-flex justify-content-around">
            <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active text-center">
                    <img class="rounded" src="{{asset('assets/img/fond/bouledogue.jpg')}}" height="300" width="300"/>
                    <img class="rounded" src="{{asset('assets/img/fond/p.jpg')}}" height="300" width="300"/>               
                    </div>
                    <div class="carousel-item text-center">
                    <img class="rounded" src="{{asset('assets/img/fond/pigeon.jpg')}}" height="300" width="300"/>
                    <img class="rounded" src="{{asset('assets/img/fond/colombe.jpg')}}" height="300" width="300"/>
                    
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only"></span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only"></span>
                </a>
                </div>
            </div>
        </div>
    </div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    
</body>
</html>

resources/views/modifyImage.blade.php
@extends('layouts.layout')

@section('title')
    Modifier une image
@endsection

@section('correction_url')../../@endsection


@section('page_contenu')
@if(session()->has('info'))
<div class="card text-white bg-success mb-3 mx-auto" style="max-width: 18rem;">
<div class="card-body">
<p class="card-text">{{ session('info') }}</p>
</div>
</div>
@endif
<div class="container">
    <div class="row shadow card text-black bg-dark w-50 mx-auto p-3"  style="background-color:rgb(27,30,31);">
        <p class="text-center display-5">Modifiez votre image</p>  
        <form action="{{route('images.update',$image->id)}}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group mt-4">
                <label for="title" class="form-label col-md-5 col-10">Titre de l'image</label>
                <input id="title" class="border form-control @error('title') is-invalid @enderror col-md-3 shadow col-6 text-light" style="background-color:rgb(24,26,27);border:1px solid rgb(50,54,56);" value="{{old('title',$image->title)}}"  name="title" type="text" placeholder="Mon animal preferé"/>
                @error('title')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group row mt-4">
                <label for="description" class="form-label col-md-5 col-10">Description</label>
                <textarea id="description" class="border form-control  @error('description') is-invalid @enderror col-md-3 shadow col-6 text-light" style="background-color:rgb(24,26,27);border:1px solid rgb(50,54,56);" value=""  name="description" type="textarea" placeholder="Je l'aime tellement">{{old('description',$image->description)}}</textarea>
                @error('description')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group row mt-4">
            <label for="id_genre" class="form-label col-md-5 col-10">Genre</label>
            <select name="id_genre" name="id_genre" value="{{old('id_genre',$image->id_genre)}}" id="id_genre" style="background-color:rgb(24,26,27);border:1px solid rgb(50,54,56);" class="text-light form-select form-control @error('id_genre') is-
invalid @enderror">
            @foreach($listeGenre as $genre)
                    <option class="text-light" value="{{$genre->id}}" {{ ( $genre->id == old('id_genre',$image->id_genre)) ? 'selected' : '' }}>{{$genre->genreName}}</option>
            @endforeach
            </select>
            
            </div>

            <div class="form-group row mt-4">
                <label for="source" name="source" class="label-file">Choisir une image</label>
                <input id="source" name="source" class="form-control @error('source') is-invalid @enderror input-file mt-3" value="{{old('source',$image->source)}}" type="file">
                @error('source')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="justify-content-end mt-4 text-center">
                <button type="submit" class="btn btn-success">Publier !</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/personalInfo.blade.php
@extends('layouts.layout')

@section('title')
    Vous
@endsection

@section('correction_url')../@endsection

@section('page_contenu')
@if(session()->has('info'))
<div class="card text-white bg-danger mb-3 mx-auto" style="max-width: 18rem;">
<div class="card-body">
<p class="card-text">{{ session('info') }}</p>
</div>
</div>
@endif
<div class="">
    <div class="text-center mt-3">
        <?php 
        $indImage = rand(1,5);
        
        ?>
        <img class="rounded-circle bg-secondary" width="200" height="200" src=<?=asset('assets/img/iconesPdp/pdp'.$indImage.
        '.jpg')?>/>
        <p class="display-4 text-white">{{$util->prenom}} {{$util->nom}}</p>
        <p class="text-white">{{$util->email}}</p>
    </div>

    <div class="text-center mt-3">
        <div class="d-flex justify-content-center">
            <div>
                <a class="px-2 text-white" class="choixContent" id="btnImageAimer" href="#" onclick="return false;">Aimées</a>
                <hr id="imageAimerSouligne" style=" border-top:3px solid white;">
            </div>
            <div>
                <a class="px-2 text-white" class="choixContent" id="btnImageCree" href="#" onclick="return false;">Crées</a>
                <hr id="imageCreeSouligne" style=" border-top:3px solid white;">
            </div>

            
        </div>

        

        <div id="images_crees">

            @if( $util->id == Auth::user()->id)
            <a class="text-center btn btn-success" href="{{route('images.create')}}">Ajouter une nouvelle image</a>
            @endif
            <?php $i=1; ?>
            <?php $nbImages=0;?>
            <div class="pin_container">
            @foreach($util->imagesCrees as $image)
            <?php
                
                if($i==1)
                {
                    
                    echo '<a href="'.route('images.show',$image->id).'" data="'.$nbImages.'" class="card card_small cardCree">';
                    $i = $i+1;
                }
                else if($i==2)
                {
                    echo '<a href="'.route('images.show',$image->id).'" data="'.$nbImages.'" class="card card_medium cardCree">';
                    $i = $i+1;
                }
                else
                {
                    echo '<a href="'.route('images.show',$image->id).'" data="'.$nbImages.'" class="card card_large cardCree">';
                    $i = 1;
                }
                
                
            ?>
                <img class="card-img-top rounded" width="400" height="500" src="{{ asset($image->source) }}" alt="">
                @if( $util->id == Auth::user()->id)
                <form action="{{route('images.destroy',$image->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                <button id=<?='boutonC'.$nbImages ?> class="bouton_supprimer btn btn-danger"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
  <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293 5.354 4.646z"/>
</svg></button>
                 </form>

                <form action="{{route('images.edit',$image->id)}}">
                    @csrf
                <button id=<?='boutonS'.$nbImages ?> class="bouton_maj btn btn-secondary"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
</svg></button>
                </form>
                @endif
                <?php $nbImages = $nbImages+1?>
                
            </a>
            @endforeach
            </div>  
        </div>


        <div id="images_aimees">
            <?php $i=1; ?>
            <?php $nbImages=0;?>
            <div class="pin_container">
            @foreach($util->imagesAimees as $image)
            <?php
                
                if($i==1)
                {
                    
                    echo '<a href="'.route('images.show',$image->id).'" data="'.$nbImages.'" class="card card_small cardAimer">';
                    $i = $i+1;
                }
                else if($i==2)
                {
                    echo '<a href="'.route('images.show',$image->id).'" data="'.$nbImages.'" class="card card_medium cardAimer">';
                    $i = $i+1;
                }
                else
                {
                    echo '<a href="'.route('images.show',$image->id).'" data="'.$nbImages.'" class="card card_large cardAimer">';
                    $i = 1;
                }
                
                
            ?>
                <img class="card-img-top rounded" width="400" height="500" src="{{ asset($image->source) }}" alt="">
                <?php $nbImages = $nbImages+1?>
                
            </a>
            @endforeach
            </div>  
        </div>

        

        

        

        
    </div>


</div>

@endsection

@section('script')
        //Section sélectionnée
        var images_crees = document.getElementById("images_crees");
        var images_aimees = document.getElementById("images_aimees");

       


        var imageCreeSouligne = document.getElementById("imageCreeSouligne");
        var imageAimerSouligne = document.getElementById("imageAimerSouligne");

        var btnImageAimerContent = function() {
            images_crees.style.display="none";
            images_aimees.style.display="contents";
            imageCreeSouligne.style.visibility="hidden";
            imageAimerSouligne.style.visibility="visible";
        };

        var btnImageCreeContent = function() {
            images_crees.style.display="contents";
            images_aimees.style.display="none";
            imageCreeSouligne.style.visibility="visible";
            imageAimerSouligne.style.visibility="hidden";
        };

        document.getElementById("btnImageAimer").addEventListener('click',btnImageAimerContent,false);
        document.getElementById("btnImageCree").addEventListener('click',btnImageCreeContent,false);




        //Boutons apparitions
        var cardAimer = document.getElementsByClassName("cardAimer");
        var cardCrees = document.getElementsByClassName("cardCree");
        var classbutton = document.getElementsByClassName("bouton_aimer");

        //Fonctions qui cachent ou font apparaître des boutons
        var visibleAimer = function() {
            var attribute = this.getAttribute("data");
            var button = document.getElementById("boutonA"+attribute);
            button.style.visibility = 'visible';
        };

        var cacherAimer = function() {
            var attribute = this.getAttribute("data");
            var button = document.getElementById("boutonA"+attribute);
            button.style.visibility = 'hidden';
        };

        var visibleCree = function() {
            var attribute = this.getAttribute("data");
            var button = document.getElementById("boutonC"+attribute);
            var buttonS = document.getElementById("boutonS"+attribute);
            button.style.visibility = 'visible';
            buttonS.style.visibility = 'visible';
        };

        var cacherCree = function() {
            var attribute = this.getAttribute("data");
            var button = document.getElementById("boutonC"+attribute);
            var buttonS = document.getElementById("boutonS"+attribute);
            button.style.visibility = 'hidden';
            buttonS.style.visibility = 'hidden';
        };


        //Initialisation des évènements pour les boutons
        /*for (var i = 0; i < cardAimer.length; i++) {
            cardAimer[i].addEventListener('mouseover', visibleAimer, false);
        }

        for (var i = 0; i < cardAimer.length; i++) {
            cardAimer[i].addEventListener('mouseout', cacherAimer, false);
        }*/

        for (var i = 0; i < cardCrees.length; i++) {
            cardCrees[i].addEventListener('mouseover', visibleCree, false);
        }

        for (var i = 0; i < cardCrees.length; i++) {
            cardCrees[i].addEventListener('mouseout', cacherCree, false);
        }
@endsection

resources/views/showImageInfo.blade.php
@extends('layouts.layout')

@section('page_titre')
{{$image->title}}
@endsection


@section('correction_url')../@endsection

@section('page_contenu')
    <div class="container-fluid mt-3">
        <div class="row">
            <div class="col-2">
                <a href="{{url()->previous()}}">
                <button type="button" class="btn btn-primary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
                    </svg>
                    Retour
                </button>
                </a>
            </div>
            <div class="col-8 bg-dark border border-rounded border-2" id="contenu_site">
                <div class="row">
                    <div class="col-6 p-0">
                        <img class="contenu_site_img" src="{{$path}}"/>
                    </div>
                    <div class="col-6">
                        <form method="post" action="../liked_image" >
                            @csrf
                            <input name="image_id" id="image_id" type="hidden" value="{{$image->id}}" />
                            <button type="submit" class="btn btn-danger mt-3">
                                @if($image_liked_state == false)
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                                    <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                                </svg>
                                @else
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                                </svg>
                                @endif
                            </button>
                        </form> 
                        <h1><strong><?php echo $image->title; ?></strong></h1>
                        <p>{{$image->description}}</p>
                        <p>Créateur : <a href="{{route('personalInfo.show',$image->user_id)}}" class="text-white">{{$image->user->nom}} {{$image->user->prenom}}</a></p>
                        <h4><?php 
                            $nb_commentaires = count($commentaires);
                            if($nb_commentaires >= 2)
                            {
                                echo $nb_commentaires." commentaires";
                            }
                            else
                            {
                                echo $nb_commentaires." commentaire";
                            } ?></h4>
                        <p>
                        @foreach($commentaires as $commentaire)
                            <strong>{{$commentaire->user->nom}} {{$commentaire->user->prenom}}</strong>  {{$commentaire->commentaire}}<br/>
                        @endforeach
                        </p>
                        <!--<p>//Mettre les commentaires ici</p>-->
                        
                        <form action="../post_comment" method="post">
                            @csrf
                            <input name="image_id" id="image_id" type="hidden" value="{{$image->id}}" />
                            <div class="form-floating">
                                <textarea class="form-control" placeholder="Leave a comment here" id="commentaire", name="commentaire"></textarea>
                                <label for="floatingTextarea" style="color:gray">Ajouter un commentaire</label>
                            </div>
                            <div class="mt-2" align="right">
                                <button type="submit" class="btn btn-primary mb-3">Terminé</button>
                            </div>
                            
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection